apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: visitor-app3:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: go-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: app
spec:
  type: NodePort  # Change to LoadBalancer if available
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080