apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: db
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None  # Stable network ID in the cluster