apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: db
spec:
  clusterIP: None  # Headless service for stable network identity
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
